[workspace]

[package]
edition = "2021"
name = "resolver"
publish = false
resolver = "1"
rust-version = "1.60"
version = "0.0.0"

[features]
default = ["web-time/default"]
serde = ["web-time/serde"]
std = ["web-time/std"]

[dependencies]
web-time = { path = "../..", default-features = false }
